version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=Finance
    networks:
      - mern-network

  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Finance
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mern-network

volumes:
  mysql_data:

networks:
  mern-network:
